---

https_proxy: https://16.85.88.10:8080
system_proxy: http://16.85.88.10:8080

openstack_img_url: http://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-disk1.img
cirros_img_url: http://download.cirros-cloud.net/0.3.5/cirros-0.3.5-x86_64-disk.img
lxd_img_url: http://cloud-images.ubuntu.com/trusty/current/trusty-server-cloudimg-amd64-root.tar.gz
img_dst: os_xenial.img

ansible_primary_user: arunt

artifacts:
    - op_services.bash
    - comm_services.bash
    - bootstrap.bash
    - bootstrapsrc
    - demorc
    - adminrc
    - openstack_onboard.bash

###Attention
###Typical Values that need change
###Attention
openstack_controller: controller
#openstack_controller_ip: 10.165.127.73
#openstack_local_ip: 10.165.127.73
###End
openstack_adminpass: nfv
openstack_region: RegionOne
openstack_commonpass: nfv

openstack_project_domain_name: default
openstack_user_domain_name: default 

#as new services start coming in, add an entry for each DB 
#required by that service. this will ensure that a database
#is created and permissions assigned as expected 

openstack_services_db: 
  keystone:
    host: localhost
    pwd: nfv
    home_dir: /etc/keystone
    primary_own: keystone
    pkgs: keystone
  glance:
    host: localhost
    pwd: nfv
    home_dir: /etc/glance
    primary_own: glance
    pkgs: glance
  nova:
    host: localhost
    pwd: nfv
    home_dir: /etc/nova
    primary_own: nova
    pkgs: nova-scheduler
  nova_api:
    host: localhost
    pwd: nfv
    home_dir: /etc/nova
    primary_own: nova
    pkgs: nova-api
  nova_cell0:
    host: localhost
    pwd: nfv
    home_dir: /etc/nova
    primary_own: nova
    pkgs: nova-placement-api
  neutron:
    host: localhost
    pwd: nfv
    home_dir: /etc/neutron
    primary_own: neutron
    pkgs: neutron-server
  cinder:
    host: localhost
    pwd: nfv
    home_dir: /etc/cinder
    primary_own: cinder
    pkgs: cinder-api

openstack_packages:
  keystone:
    - keystone
  glance:
    - glance
  nova:
    - nova-api
    - nova-conductor
    - nova-consoleauth
    - nova-novncproxy
    - nova-scheduler
    - nova-placement-api
  
openstack_keystone_config:
  keystone_bootstrap:
    admin: 35357
    internal: 5000
    public: 5000
    conf: /etc/keystone/keystone.conf
openstack_services_config:
  glance:
    domain: default
    svc_pass: nfv
    svc_descr: "OpenStack-Image"
    port: 9292
    svc_name: image
    conf: /etc/glance/glance-api.conf
  nova:
    domain: default
    svc_pass: nfv
    svc_descr: "OpenStack-Compute"
    port: 8774/v2.1
    svc_name: compute
  placement:
    domain: default
    svc_pass: nfv
    svc_descr: "OpenStack-Placement"
    port: 8778
    svc_name: placement
  neutron:
    domain: default
    svc_pass: nfv
    svc_descr: "OpenStack-Network"
    port: 9696
    svc_name: network
  cinderv2:
    domain: default
    svc_pass: nfv
    svc_descr: "OpenStack-Block-Storage-2"
    port: 8776/v2/%\(project_id\)s
    svc_name: volumev2
  cinderv3:
    domain: default
    svc_pass: nfv
    svc_descr: "OpenStack-Block-Storage-3"
    port: 8776/v3/%\(project_id\)s
    svc_name: volumev3

#glance variables
keystone_config_file: /etc/keystone/keystone.conf
glance_api_config_file: /etc/glance/glance-api.conf
glance_registry_config_file: /etc/glance/glance-registry.conf

nova_api_config_file: /etc/nova/nova.conf

neutron_api_config_file: /etc/neutron/neutron.conf
neutron_ml2_config_file: /etc/neutron/plugins/ml2/ml2_conf.ini
neutron_dhcp_config_file: /etc/neutron/dhcp_agent.ini
neutron_lbr_config_file: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
neutron_metadata_config_file: /etc/neutron/metadata_agent.ini
neutron_core_plugin: ml2
neutron_data_interface: eth1

cinder_api_config_file: /etc/cinder/cinder.conf

#provider_networks or self_service_networks
neutron_networking: provider_networks


nova_services:
  - nova-api
  - nova-conductor
  - nova-consoleauth
  - nova-novncproxy
  - nova-scheduler

nova_packages:
  - nova-api
  - nova-conductor
  - nova-consoleauth
  - nova-novncproxy
  - nova-scheduler
  - nova-placement-api 

nova_dbs:
  - nova_api
  - nova
  - nova_cell10

neutron_packages:
  - neutron-server
  - neutron-plugin-ml2
  - neutron-linuxbridge-agent
  - neutron-dhcp-agent
  - neutron-metadata-agent
  - neutron-l3-agent
  
neutron_services:
  - neutron-server
  - neutron-linuxbridge-agent
  - neutron-dhcp-agent
  - neutron-metadata-agent
  - neutron-l3-agent

cinder_packages:
  - cinder-api
  - cinder-scheduler
cinder_services:
  - cinder-scheduler

#TODO: re-write individal config file settings as a list and use 
#nested sub elements
glance_files:
  - /etc/glance/glance-api.conf
  - /etc/glance/glance-registry.conf
glance_var:
  - name: apiconfig
    files:
      - /etc/glance/glance-api.conf
      - /etc/glance/glance-registry.conf 
    keystone_authtoken: 
      auth_uri: "http://{{ openstack_controller }}:5000"
      auth_url: "http://{{ openstack_controller }}:35357"
dashboard_packages:
  - openstack-dashboard
