---
- hosts: remote-nodes
  tasks:
#Pre-req
# User arunt needs to be sudo capable without passwords

#TODO
#  - name: copy security keys from build server to remote host

#  - name: setup git clone in remote host
#    git: repo=https://arun.thulasi:{{ token }}@github.hpe.com/arun-thulasi/nfv-tools-git.git dest={{ git_dest }}

#TODO
#  - name: copy variable files and host files to /etc/ansible on the target host


  - name: list existing network
    virt_net: command=list_nets

  - name: pick up xml files and create various network domains 
    virt_net: 
      command: define 
      name: "{{ item.value.name }}"
      xml: "{{lookup('template','{{ item.value.location }}')}}"
    with_dict: "{{ net_vars }}"

  - name: mark all networks as autostart
    virt_net: autostart=yes name={{ item.value.name }} 
    with_dict: "{{ net_vars }}"

  - name: start all networks
    virt_net: command=create name={{ item.value.name }} 
    with_dict: "{{ net_vars }}"








