Vagrant.configure("2") do |config|
  config.vm.define "web" do |web|
    web.vm.box = "ceph/ubuntu-xenial"
    web.vm.hostname = 'control'
    web.vm.box_url = "ceph/ubuntu-xenial"


    web.vm.network :private_network, ip: "192.168.56.101"

  end

  config.vm.define "db" do |db|
    db.vm.box = "ceph/ubuntu-xenial"
    db.vm.hostname = 'compute'
    db.vm.box_url = "ceph/ubuntu-xenial"

    db.vm.network :private_network, ip: "192.168.56.102"

  end
end
