Vagrant.configure("2") do |config|

  config.vm.define "bootstrap" do |bootstrap|
    bootstrap.vm.box = "ubuntu/bionic64"
    bootstrap.vm.hostname = "bootstrap"
    bootstrap.vm.network "private_network", ip: "192.168.50.3"
    bootstrap.vm.provision "file", source: "~/estack/keys/vagrant_vms.pub", destination: "/home/vagrant/.ssh/authorized_keys_2"
    bootstrap.vm.provision "shell", inline: "sudo /bin/cp /home/vagrant/.ssh/authorized_keys_2 /home/ubuntu/.ssh/authorized_keys"
  end

  config.vm.define "master" do |master|
    master.vm.box = "ubuntu/bionic64"
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "192.168.50.31"
    master.vm.provision "file", source: "~/estack/keys/vagrant_vms.pub", destination: "/home/vagrant/.ssh/authorized_keys_2"
    master.vm.provision "shell", inline: "sudo /bin/cp /home/vagrant/.ssh/authorized_keys_2 /home/ubuntu/.ssh/authorized_keys"
  end

  config.vm.define "worker1" do |worker1|
    worker1.vm.box = "ubuntu/bionic64"
    worker1.vm.hostname = "worker1"
    worker1.vm.network "private_network", ip: "192.168.50.32"
    worker1.vm.provision "file", source: "~/estack/keys/vagrant_vms.pub", destination: "/home/vagrant/.ssh/authorized_keys_2"
    worker1.vm.provision "shell", inline: "sudo /bin/cp /home/vagrant/.ssh/authorized_keys_2 /home/ubuntu/.ssh/authorized_keys"
  end

  config.vm.define "worker2" do |worker2|
    worker2.vm.box = "ubuntu/bionic64"
    worker2.vm.hostname = "worker2"
    worker2.vm.network "private_network", ip: "192.168.50.33"
    worker2.vm.provision "file", source: "~/estack/keys/vagrant_vms.pub", destination: "/home/vagrant/.ssh/authorized_keys_2"
    worker2.vm.provision "shell", inline: "sudo /bin/cp /home/vagrant/.ssh/authorized_keys_2 /home/ubuntu/.ssh/authorized_keys"
  end
  config.vm.define "worker3" do |worker3|
    worker3.vm.box = "ubuntu/bionic64"
    worker3.vm.hostname = "worker3"
    worker3.vm.network "private_network", ip: "192.168.50.34"
    worker3.vm.provision "file", source: "~/estack/keys/vagrant_vms.pub", destination: "/home/vagrant/.ssh/authorized_keys_2"
    worker3.vm.provision "shell", inline: "sudo /bin/cp /home/vagrant/.ssh/authorized_keys_2 /home/ubuntu/.ssh/authorized_keys"
  end
end
