Vagrant.configure("2") do |config|

  config.vm.define "bootstrap" do |bootstrap|
    bootstrap.vm.box = "ubuntu/bionic64"
    bootstrap.vm.hostname = "bootstrap"
    bootstrap.vm.network "private_network", ip: "192.168.50.3"
  end

  config.vm.define "master" do |master|
    master.vm.box = "ubuntu/bionic64"
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "192.168.50.4"
  end

  config.vm.define "worker1" do |worker1|
    worker1.vm.box = "ubuntu/bionic64"
    worker1.vm.hostname = "worker1"
    worker1.vm.network "private_network", ip: "192.168.50.15"
  end

  config.vm.define "worker2" do |worker2|
    worker2.vm.box = "ubuntu/bionic64"
    worker2.vm.hostname = "worker2"
    worker2.vm.network "private_network", ip: "192.168.50.16"
  end
end
