---
  - name: create system directory for docker to use http proxy
    file: 
      path: "{{ docker_systemd_dir }}" 
      state: directory
    become: true

  - name: create system file for docker to use http proxy
    blockinfile: 
      dest: "{{ docker_systemd_file }}"
      create: yes
      block: |
        [Service]
        Environment="HTTP_PROXY=http://16.85.88.10:8080/"
    become: true


  - name: create docker group to bypass sudo requirements
    group:
      name: "{{ docker_group }}"
      state: present

  - name: add user to docker group to bypass sudo requirements
    user:
      name: "{{ docker_user }}"
      group: "{{ docker_group }}"
    become: true


  - name: configure ufw to forward packets
    lineinfile:
      dest: "{{ ufw_settings_file }}"
      regexp: ^DEFAULT_FORWARD_POLICY
      line: DEFAULT_FORWARD_POLICY="ACCEPT"
    become: true

  - name: allow docker traffic to be forwarded
    ufw:
      rule: allow
      port: "{{ item }}"
    with_items:
      - 2375
      - 22
    become: true

  - name: do a systemctl daemon-reload
    shell: systemctl daemon-reload
    become: true

  - name: restart all services and make them persistent
    service: 
      name: "{{ item }}"
      state: restarted
      enabled: yes
    with_items:
      - docker
      - ufw
    become: true 
